## name: Gruvbox Dark
## author: morhetz (palette)
## license: MIT
## blurb: Retro groove — warm, medium-contrast dark theme (matches tmux gruvbox)

foreground               #ebdbb2
background               #282828
selection_foreground     #ebdbb2
selection_background     #665c54

cursor                   #ebdbb2
cursor_text_color        #282828

url_color                #83a598

active_tab_foreground    #282828
active_tab_background    #d79921
inactive_tab_foreground  #a89984
inactive_tab_background  #3c3836

# black
color0   #282828
color8   #928374

# red
color1   #cc241d
color9   #fb4934

# green
color2   #98971a
color10  #b8bb26

# yellow
color3   #d79921
color11  #fabd2f

# blue
color4   #458588
color12  #83a598

# magenta
color5   #b16286
color13  #d3869b

# cyan
color6   #689d6a
color14  #8ec07c

# white
color7   #a89984
color15  #ebdbb2
