hide_window_decorations yes
font_family JetBrainsMono NF
cursor_blink_interval 0
background_opacity 0.9
cursor_trail 1

# Vim-style cursor navigation (alt + h/j/k/l)
map alt+h send_key left
map alt+j send_key down
map alt+k send_key up
map alt+l send_key right


# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
