"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[──>](bold green)'

[package]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
truncation_symbol = '…/'
